/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 frame.gltf 
Author: Fred Drabble (https://sketchfab.com/FredDrabble)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/picture-frame-1520-dimensions-2a75286422e64948b1d6626bc9c6d47d
Title: PICTURE FRAME 15*20 dimensions
*/



import React from 'react'
import { useGLTF, useTexture } from '@react-three/drei'
import * as THREE from 'three'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/frame.gltf')
    const texture = useTexture(props.paintingURL)
    return (

        <group {...props} dispose={null}>
            <group rotation={[0, 0, 0]} position={[0,1,0]}>
                <group rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={0.1}>
                    <mesh geometry={nodes.painting_aiStandardSurface1_0.geometry} position={[0, -0.884, 0]}>
                        <meshStandardMaterial map={texture} side={THREE.DoubleSide}/>
                    </mesh>
          <mesh geometry={nodes.frame_lambert1_0.geometry} material={materials.lambert1} position={[0, 0.86, 0]} scale={[0.942, 0.89, 0.942]} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/frame.gltf')
